[package]
name = "tupl"
description = "Perform generic operations on tuples."
authors = ["Dragoteryx"]
version = "0.4.0"
edition = "2021"
rust-version = "1.65"
repository = "https://github.com/Dragoteryx/tupl"
license = "MIT"
keywords = ["tuple"]
